/** A curated list of common five-letter English words — doubles as both the daily answer
 *  pool and the accepted-guess dictionary, keeping the game dependency-free. */
export const WORD_LIST: string[] = [
  'apple', 'board', 'brain', 'bread', 'brick', 'bring', 'build', 'chair', 'charm', 'chase',
  'cheap', 'check', 'chess', 'chief', 'child', 'claim', 'class', 'clean', 'clear', 'climb',
  'clock', 'close', 'cloud', 'coach', 'coast', 'could', 'count', 'court', 'cover', 'craft',
  'crash', 'crazy', 'cream', 'crowd', 'crown', 'dance', 'death', 'delay', 'depth', 'doubt',
  'draft', 'drama', 'dream', 'dress', 'drink', 'drive', 'eager', 'early', 'earth', 'elite',
  'empty', 'enemy', 'enjoy', 'enter', 'equal', 'error', 'event', 'every', 'exact', 'exist',
  'extra', 'faith', 'false', 'fault', 'fiber', 'field', 'fifth', 'fifty', 'fight', 'final',
  'first', 'fixed', 'flash', 'fleet', 'floor', 'fluid', 'focus', 'force', 'forth', 'forty',
  'forum', 'found', 'frame', 'frank', 'fraud', 'fresh', 'front', 'fruit', 'fully', 'funny',
  'giant', 'given', 'glass', 'globe', 'grace', 'grade', 'grand', 'grant', 'grass', 'great',
  'green', 'gross', 'group', 'grown', 'guard', 'guess', 'guest', 'guide', 'happy', 'harsh',
  'heart', 'heavy', 'hence', 'horse', 'hotel', 'house', 'human', 'ideal', 'image', 'index',
  'inner', 'input', 'issue', 'ivory', 'jelly', 'joint', 'judge', 'juice', 'known', 'label',
  'labor', 'large', 'laser', 'later', 'laugh', 'layer', 'learn', 'lease', 'least', 'leave',
  'legal', 'level', 'light', 'limit', 'links', 'lives', 'local', 'logic', 'loose', 'lower',
  'lucky', 'lunch', 'magic', 'major', 'maker', 'march', 'match', 'maybe', 'mayor', 'meant',
  'media', 'metal', 'might', 'minor', 'minus', 'mixed', 'model', 'money', 'month', 'moral',
  'motor', 'mount', 'mouse', 'mouth', 'movie', 'music', 'needs', 'never', 'newly', 'night',
  'noise', 'north', 'noted', 'novel', 'nurse', 'occur', 'ocean', 'offer', 'often', 'order',
  'other', 'ought', 'outer', 'owner', 'panel', 'paper', 'party', 'peace', 'phase', 'phone',
  'photo', 'piano', 'piece', 'pilot', 'pitch', 'place', 'plain', 'plane', 'plant', 'plate',
  'point', 'pound', 'power', 'press', 'price', 'pride', 'prime', 'print', 'prior', 'prize',
  'proof', 'proud', 'prove', 'queen', 'quick', 'quiet', 'quite', 'radio', 'raise', 'range',
  'rapid', 'ratio', 'reach', 'ready', 'realm', 'rebel', 'refer', 'relax', 'reply', 'right',
  'rival', 'river', 'robot', 'roman', 'rough', 'round', 'route', 'royal', 'rural', 'scale',
  'scene', 'scope', 'score', 'sense', 'serve', 'seven', 'shade', 'shake', 'shall', 'shape',
  'share', 'shark', 'sharp', 'sheet', 'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock',
  'shoot', 'short', 'shown', 'sight', 'since', 'sixth', 'skill', 'sleep', 'slide', 'small',
  'smart', 'smile', 'smoke', 'snake', 'solid', 'solve', 'sorry', 'sound', 'south', 'space',
  'spare', 'speak', 'speed', 'spend', 'spent', 'split', 'spoke', 'sport', 'staff', 'stage',
  'stake', 'stand', 'start', 'state', 'steam', 'steel', 'stick', 'still', 'stock', 'stone',
  'store', 'storm', 'story', 'strip', 'stuck', 'study', 'stuff', 'style', 'sugar', 'suite',
  'super', 'sweet', 'swift', 'swing', 'sword', 'table', 'taken', 'taste', 'teach', 'teeth',
  'terms', 'thank', 'theme', 'there', 'these', 'thick', 'thing', 'think', 'third', 'those',
  'three', 'threw', 'throw', 'thumb', 'tight', 'timer', 'times', 'tired', 'title', 'today',
  'token', 'topic', 'total', 'touch', 'tough', 'tower', 'track', 'trade', 'train', 'treat',
  'trend', 'trial', 'tribe', 'trick', 'tried', 'tries', 'truck', 'truly', 'trust', 'truth',
  'twice', 'under', 'union', 'unity', 'until', 'upper', 'upset', 'urban', 'usage', 'usual',
  'valid', 'value', 'video', 'virus', 'visit', 'vital', 'vivid', 'voice', 'waste', 'watch',
  'water', 'wheat', 'wheel', 'where', 'which', 'while', 'white', 'whole', 'whose', 'woman',
  'world', 'worry', 'worse', 'worst', 'worth', 'would', 'wound', 'write', 'wrong', 'wrote',
  'yield', 'young', 'youth',
]
